Traceback (most recent call last):
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/client.py", line 780, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/util.py", line 97, in ensure_async
    result = await obj
  File "/home/arash/py3/lib/python3.10/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arash/py3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/client.py", line 1006, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/client.py", line 804, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/home/arash/py3/lib/python3.10/site-packages/nbclient/client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['linear_probe = LinearProbe().to(device)', "params_to_optimize = [{'params': [p for p in linear_probe.fc.parameters()]}]", 'momentum = 0.9', 'learning_rate = 0.1', 'weight_decay = 1e-4']
...
['    train_log = epoch_loop(linear_probe, train_loader, criterion, optimizer)', '     ', "    print('[%.3d] loss=%.4f     acc=%0.2f' % (epoch, np.mean(train_log[1]), np.mean(train_log[0])))", "    train_logs['acc'].append(np.mean(train_log[0]))", "    train_logs['loss'].append(np.mean(train_log[1]))"]
-------------------

